name: flutter_appcenter_bundle
description: This plugin currently bundles AppCenter Analytics, Crashes and Distribute. To learn more about AppCenter, go to https://aka.ms/appcenterdocs
version: 3.3.2
homepage: https://github.com/hanabi1224/flutter_appcenter_bundle
publish_to: https://pub.dev/

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: any
  test: any

flutter:
  plugin:
    platforms:
      android:
        package: com.github.hanabi1224.flutter_appcenter_bundle
        pluginClass: FlutterAppcenterBundlePlugin
      ios:
        pluginClass: FlutterAppcenterBundlePlugin
